name: rapidjson
channels:
  - conda-forge
dependencies:
  - numpy
  # - c-compiler
  # - cxx-compiler
  # - fortran-compiler
  - gcovr < 5.1.0
  - Jinja2 < 3.1.0
  - pyyaml
  # - zeromq
  - cmocka
  - lcov
  - cmake
  - openmpi
  - openmp
  - pytest
  - flask
  - gunicorn