name: rapidjson
channels:
  - conda-forge
dependencies:
  - numpy < 2.0.0
  # - c-compiler
  # - cxx-compiler
  # - fortran-compiler
  - gcovr # < 5.1.0
  - Jinja2 < 3.1.0
  - pyyaml
  # - zeromq
  - lcov
  - cmake
  - openmpi
  - llvm-openmp
  - pytest
  - flask
