#pragma once

enum COMM_TYPE {
    NULL_COMM, IPC_COMM, ZMQ_COMM,
    SERVER_COMM, CLIENT_COMM,
    ASCII_FILE_COMM, ASCII_TABLE_COMM, ASCII_TABLE_ARRAY_COMM,
    MPI_COMM
};
enum DIRECTION {
    SEND, NONE, RECV
};

enum DTYPE {
    T_BOOLEAN, T_INTEGER, T_NULL, T_NUMBER, T_STRING, T_ARRAY, T_OBJECT,
    T_DIRECT, T_1DARRAY, T_NDARRAY, T_SCALAR, T_FLOAT, T_UINT, T_INT, T_COMPLEX,
    T_BYTES, T_UNICODE, T_PLY, T_OBJ,
    T_CLASS, T_FUNCTION, T_INSTANCE, T_SCHEMA, T_ANY
};

