#pragma once
//#include "AsciiFileComm.hpp"
//#include "AsciiTableComm.hpp"
#include "ClientComm.hpp"
#include "DefaultComm.hpp"
#include "IPCComm.hpp"
#include "MPIComm.hpp"
#include "ServerComm.hpp"
#include "ZMQComm.hpp"
