name = "YggInterface"
uuid = "2b3f9ead-a823-4903-90ba-14c5fb9635c6"
authors = ["Meagan Lang"]
version = "1.0.0-DEV"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
