function(select_targets output_var)
  set(multiValueArgs LIBRARIES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  set(targets)
  foreach(lib IN LISTS ARGS_LIBRARIES)
    if (TARGET ${lib})
      list(APPEND targets ${lib})
    endif()
  endforeach()
  set(${output_var} ${targets} PARENT_SCOPE)
endfunction()

function(generate_file filename contents)
  set(options NO_CONFIG ALLOW_EMPTY)
  set(oneValueArgs OUTPUT_VAR DIRECTORY CUSTOM_TARGET)
  set(multiValueArgs)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_DIRECTORY)
    set(ARGS_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  if(NOT IS_ABSOLUTE "${filename}")
    cmake_path(
      APPEND ARGS_DIRECTORY "${filename}"
      OUTPUT_VARIABLE filename
    )
  endif()
  if(NOT (contents OR ARGS_ALLOW_EMPTY OR ARGS_CUSTOM_TARGET))
    if(ARGS_OUTPUT_VAR)
      set(${ARGS_OUTPUT_VAR} "" PARENT_SCOPE)
    endif()
    message(DEBUG "${filename} will not be generated because it would be empty")
    return()
  endif()
  message(DEBUG "Generating ${filename} with CONTENTS = ${contents}")
  if(ARGS_NO_CONFIG)
    file(
      GENERATE OUTPUT "${filename}"
      CONTENT "${contents}"
    )
  else()
    file(
      GENERATE OUTPUT "${filename}.$<CONFIG>"
      CONTENT "${contents}"
    )
    add_custom_command(
      COMMAND ${CMAKE_COMMAND} "-E" "copy_if_different" "${filename}.$<CONFIG>" "${filename}"
      VERBATIM
      # PRE_BUILD Not supported by this version of add_custom_command
      DEPENDS  "${filename}.$<CONFIG>"
      OUTPUT   "${filename}"
      COMMENT  "creating ${filename} file ({event: PRE_BUILD}, {filename: ${filename}})"
    )
  endif()
  if(ARGS_OUTPUT_VAR)
    set(${ARGS_OUTPUT_VAR} ${filename} PARENT_SCOPE)
  endif()
  if(ARGS_CUSTOM_TARGET)
    add_custom_target("${ARGS_CUSTOM_TARGET}" DEPENDS ${filename})
  endif()
endfunction()

function(inspect_exports_file filename output_var)
  set(libregex "add_library\\([ \t\r\n]*([A-Za-z0-9_]+)[ \t\r\n]+.+\\)")
  file(STRINGS "${filename}" matches REGEX "${libregex}")
  foreach(match IN LISTS matches)
    string(REGEX MATCH "${libregex}" x "${match}")
    list(APPEND ${output_var} ${CMAKE_MATCH_1})
  endforeach()
  set(${output_var} ${${output_var}} PARENT_SCOPE)
endfunction()

function(get_local_dependencies target output_var)
  set(options DONT_RECURSE)
  set(oneValueArgs)
  set(multiValueArgs)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  get_target_property(target_deps ${target} INTERFACE_LINK_LIBRARIES)
  foreach(dep IN LISTS target_deps)
    if(NOT TARGET ${dep})
      continue()
    endif()
    get_target_property(dep_imported ${dep} IMPORTED)
    if(dep_imported)
      continue()
    endif()
    list(APPEND ${output_var} ${dep})
    if(NOT ARGS_DONT_RECURSE)
      get_local_dependencies(${dep} ${output_var})
    endif()
  endforeach()
  set(${output_var} ${${output_var}} PARENT_SCOPE)
endfunction()

function(export_targets_to_file filename)
  set(options)
  set(oneValueArgs)
  set(multiValueArgs TARGETS)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  set(targets ${ARGS_TARGETS})
  foreach(target IN LISTS ARGS_TARGETS)
    get_local_dependencies(${target} targets)
  endforeach()
  list(REMOVE_DUPLICATES targets)
  message(DEBUG "export_targets_to_file: targets = ${targets}")
  export(
    TARGETS ${targets}
    FILE "${filename}"
    # EXPORT_LINK_INTERFACE_LIBRARIES
  )
endfunction()

function(import_targets_from_file filename)
  set(options)
  set(oneValueArgs IMPORTED_TARGETS)
  set(multiValueArgs)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  include(${filename})
  if(ARGS_IMPORTED_TARGETS)
    inspect_exports_file(${filename} ${ARGS_IMPORTED_TARGETS})
    set(${ARGS_IMPORTED_TARGETS} ${${ARGS_IMPORTED_TARGETS}} PARENT_SCOPE)
  endif()
endfunction()

function(generate_implicit_libraries_file language target_file)
  set(options LANGUAGE_ONLY)
  set(multiValueArgs EXTRA_LIBRARIES EXTRA_DIRECTORIES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  set_options_to_names(ARGS LANGUAGE_ONLY)
  include(GeneralTools)
  include(BuildTools)
  show_implicit_libraries(PREFIX "TODO-EXTERNAL: ")
  get_implicit_libraries(${language} implicitlibs ${ARGS_LANGUAGE_ONLY})
  list(APPEND ARGS_EXTRA_LIBRARIES ${implicitlibs})
  list(REMOVE_DUPLICATES ARGS_EXTRA_LIBRARIES)
  # list(APPEND ARGS_EXTRA_LIBRARIES ${CMAKE_${language}_IMPLICIT_LINK_LIBRARIES})
  list(APPEND ARGS_EXTRA_DIRECTORIES ${CMAKE_${language}_IMPLICIT_LINK_DIRECTORIES})
  generate_target_file(
    ${target_file} NO_CONFIG
    EXTRA_LIBRARIES ${ARGS_EXTRA_LIBRARIES}
    EXTRA_DIRECTORIES ${ARGS_EXTRA_DIRECTORIES}
    ${ARGS_UNPARSED_ARGUMENTS}
  )
endfunction()

function(generate_target_file target_file)
  include(SearchTools)
  set(options NO_CONFIG ALLOW_EMPTY CREATE_MSVC_IMPORT FULL_LIBRARIES)
  set(oneValueArgs OUTPUT_VAR DIRECTORY CUSTOM_TARGET)
  set(multiValueArgs TARGETS EXTRA_LIBRARIES EXTRA_DIRECTORIES
      FULL_LIBRARY_SUFFIXES FULL_LIBRARY_IGNORE_SUFFIXES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT WIN32)
    set(ARGS_CREATE_MSVC_IMPORT OFF)
  endif()
  set_options_to_names(ARGS CREATE_MSVC_IMPORT)
  collect_arguments(
    FILE_ARGS ARGS "${options}"
    NO_CONFIG ALLOW_EMPTY OUTPUT_VAR DIRECTORY CUSTOM_TARGET
  )
  message(DEBUG "${target_file}: ARGS_TARGETS = ${ARGS_TARGETS}")
  list(APPEND FILE_ARGS ${ARGS_UNPARSED_ARGUMENTS})
  if(ARGS_EXTRA_LIBRARIES AND (ARGS_FULL_LIBRARIES OR ARGS_CREATE_MSVC_IMPORT))
    find_libraries(
      LIBRARIES ${ARGS_EXTRA_LIBRARIES}
      DIRECTORIES ${ARGS_EXTRA_DIRECTORIES}
      OUTPUT full_libraries
      MISSING libnames ${ARGS_CREATE_MSVC_IMPORT}
      INCLUDE_SUFFIXES ${ARGS_FULL_LIBRARY_SUFFIXES}
      IGNORE_SUFFIXES ${ARGS_FULL_LIBRARY_IGNORE_SUFFIXES}
    )
  else()
    set(libnames ${ARGS_EXTRA_LIBRARIES})
  endif()
  set(CONTENTS)
  if(ARGS_TARGETS OR libnames OR full_libraries OR ARGS_EXTRA_DIRECTORIES)
    set(CONTENTS "LIBRARIES;${libnames};FULL_LIBRARIES;${full_libraries};DIRECTORIES;${ARGS_EXTRA_DIRECTORIES}")
    if(ARGS_TARGETS)
      set(CONTENTS "${CONTENTS};LIBRARIES;${ARGS_TARGETS};DIRECTORIES;$<TARGET_FILE_DIR:${ARGS_TARGETS}>")
    endif()
  endif()
  generate_file("${target_file}" "${CONTENTS}" ${FILE_ARGS})
  if(ARGS_OUTPUT_VAR)
    set(${OUTPUT_VAR} "${${ARGS_OUTPUT_VAR}}" PARENT_SCOPE)
  endif()
endfunction()

function(target_link_from_file target scope)
  include(SearchTools)
  set(multiValueArgs FILES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if (ARGS_FILES)
    set(files ${ARGS_FILES})
  else()
    set(files ${ARGS_UNPARSED_ARGUMENTS})
  endif()
  set(FULL_LIBS)
  set(LIBS)
  set(DIRS)
  foreach(src IN LISTS files)
    set(curr)
    set(lines)
    if(EXISTS ${src})
      file(READ ${src} lines)
    endif()
    message(DEBUG "target_link_from_file: ${src}: ${lines}")
    foreach(x IN LISTS lines)
      if(x STREQUAL "LIBRARIES")
        set(curr LIBS)
      elseif(x STREQUAL "FULL_LIBRARIES")
        set(curr FULL_LIBS)
      elseif(x STREQUAL "DIRECTORIES")
        set(curr DIRS)
      elseif(NOT curr)
        message(FATAL_ERROR "Type for current line not set")
      elseif(x)
        list(APPEND ${curr} ${x})
      endif()
    endforeach()
  endforeach()
  set(all_libs)
  if(LIBS)
    find_libraries(LIBRARIES ${LIBS} DIRECTORIES ${DIRS} OUTPUT LIBS)
    list(APPEND all_libs ${LIBS})
  endif()
  if(FULL_LIBS)
    list(APPEND all_libs ${FULL_LIBS})
  endif()
  if (all_libs)
    if(scope STREQUAL "IMPORTED")
      get_target_property(EXISTING_LIBS ${target} INTERFACE_LINK_LIBRARIES)
      if(EXISTING_LIBS)
        list(PREPEND all_libs ${EXISTING_LIBS})
      endif()
      set_target_properties(${target} PROPERTIES
                            INTERFACE_LINK_LIBRARIES "${all_libs}")
    else()
      target_link_libraries(${target} ${scope} ${all_libs})
    endif()
  endif()
  if(DIRS)
    if(scope STREQUAL "IMPORTED")
      get_target_property(EXISTING_DIRS ${target} INTERFACE_LINK_DIRECTORIES)
      if(EXISTING_DIRS)
        list(PREPEND DIRS ${EXISTING_DIRS})
      endif()
      set_target_properties(${target} PROPERTIES
                            INTERFACE_LINK_DIRECTORIES "${DIRS}")
    else()
      target_link_directories(${target} ${scope} ${DIRS})
    endif()
  endif()
endfunction()
