# https://stackoverflow.com/questions/32183975/how-to-print-all-the-properties-of-a-target-in-cmake
# Get all propreties that cmake supports
if(NOT CMAKE_PROPERTY_LIST)
  execute_process(
    COMMAND cmake --help-property-list
    OUTPUT_VARIABLE CMAKE_PROPERTY_LIST
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  # Convert command output into a CMake list
  string(REGEX REPLACE ";" "\\\\;" CMAKE_PROPERTY_LIST "${CMAKE_PROPERTY_LIST}")
  string(REGEX REPLACE "\n" ";" CMAKE_PROPERTY_LIST "${CMAKE_PROPERTY_LIST}")
  list(REMOVE_DUPLICATES CMAKE_PROPERTY_LIST)
endif()

macro(cmakevar2cmakecliarg opt OUTPUT_LIST_VARIABLE)
  if(${opt} AND NOT ${OUTPUT_LIST_VARIABLE} MATCHES "-D${opt}=")
    list(LENGTH ${opt} opt_len)
    if (${opt_len} GREATER 1)
      list(JOIN ${opt} "\\\\;" tmp)
      list(APPEND ${OUTPUT_LIST_VARIABLE} "-D${opt}=${tmp}")
    else()
      list(APPEND ${OUTPUT_LIST_VARIABLE} "-D${opt}=${${opt}}")
    endif()
  endif()
endmacro()

macro(cmakevars2cmakecliargs OUTPUT_LIST_VARIABLE)
  foreach(opt ${ARGN})
    cmakevar2cmakecliarg(${opt} ${OUTPUT_LIST_VARIABLE})
  endforeach()
endmacro()

function(split_string INPUT PATTERN OUTPUT)
  set(rem "${INPUT}")
  set(idx 0)
  set(parts)
  string(LENGTH "${PATTERN}" PATTERN_LEN)
  while(NOT ${idx} EQUAL "-1")
    string(FIND "${rem}" "${PATTERN}" idx)
    if(${idx} EQUAL "-1")
      list(APPEND parts "${rem}")
    else()
      string(SUBSTRING "${rem}" 0 ${idx} part)
      list(APPEND parts "${part}")
      math(EXPR idxp1 "${idx}+${PATTERN_LEN}")
      string(SUBSTRING "${rem}" ${idxp1} -1 rem)
    endif()
  endwhile()
  set(${OUTPUT} ${parts} PARENT_SCOPE)
endfunction()

macro(cmake_parse_arguments_key_value_pattern2regex_full ARGS_PREFIX PATTERN_VAR DEFAULT)
  list(APPEND options ${PATTERN_VAR}_IS_REGEX ${PATTERN_VAR}_CHECKED)
  list(APPEND oneValueArgs ${PATTERN_VAR} ${PATTERN_VAR}_REPLACE_SEMICOLON)
  cmake_parse_arguments(${ARGS_PREFIX} "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  set(PATTERN_PREFIX "${ARGS_PREFIX}_${PATTERN_VAR}")
  if(NOT ${PATTERN_PREFIX}_REPLACE_SEMICOLON)
    set(${PATTERN_PREFIX}_REPLACE_SEMICOLON "-SEMICOLON-")
  endif()
  if((NOT ${PATTERN_PREFIX}) OR (${PATTERN_PREFIX} STREQUAL "ON"))
    set(${PATTERN_PREFIX} "${DEFAULT}")
    set(${PATTERN_PREFIX}_IS_REGEX OFF)
    set(${PATTERN_PREFIX}_CHECKED PATTERN_CHECKED)
  endif()
  if(${PATTERN_PREFIX}_IS_REGEX)
    set(${PATTERN_PREFIX}_REGEX "${${PATTERN_PREFIX}}")
    set(${PATTERN_PREFIX})
    set(${PATTERN_PREFIX}_IS_REGEX OFF)
    set(${PATTERN_PREFIX}_CHECKED)
  else()
    if(NOT ${PATTERN_PREFIX}_CHECKED)
      if((NOT (${PATTERN_PREFIX} MATCHES "<key>" AND
               ${PATTERN_PREFIX} MATCHES "<value>")) OR
         (${PATTERN_VAR}_ALLOW_EITHER_KEY_OR_VALUE AND
          NOT (${PATTERN_PREFIX} MATCHES "<key>" OR
               ${PATTERN_PREFIX} MATCHES "<value>")))
        message(FATAL_ERROR "Pattern \"${${PATTERN_PREFIX}}\" does not contain required \"<key>\" and \"<value>\"")
      endif()
    endif()
    set(${PATTERN_PREFIX}_CHECKED ${PATTERN_VAR}_CHECKED)
    set(${PATTERN_PREFIX}_REGEX "${${PATTERN_PREFIX}}")
    string(REPLACE "<key>" "([A-Za-z0-9_]+)" ${PATTERN_PREFIX}_REGEX "${${PATTERN_PREFIX}_REGEX}")
    string(REPLACE "<value>" "([^\;]*)" ${PATTERN_PREFIX}_REGEX "${${PATTERN_PREFIX}_REGEX}")
  endif()
  set(${PATTERN_PREFIX}_CHILD_ARGS_PATTERN
      PATTERN "${${PATTERN_PREFIX}}" PATTERN_CHECKED
      PATTERN_REPLACE_SEMICOLON "${${PATTERN_PREFIX}_REPLACE_SEMICOLON}")
  set(${PATTERN_PREFIX}_CHILD_ARGS_REGEX
      PATTERN "${${PATTERN_PREFIX}_REGEX}" PATTERN_IS_REGEX
      PATTERN_REPLACE_SEMICOLON "${${PATTERN_PREFIX}_REPLACE_SEMICOLON}")
endmacro()

macro(cmake_parse_arguments_key_value_pattern2regex PREFIX)
  cmake_parse_arguments_key_value_pattern2regex_full(${PREFIX} PATTERN "<key>=<value>" ${ARGN})
endmacro()

function(extract_key_value CONTENTS OUTPUT_KEY OUTPUT_VAL)
  set(options REQUIRED)
  set(oneValueArgs)
  set(multiValueArgs)
  cmake_parse_arguments_key_value_pattern2regex(ARGS ${ARGN})
  string(REGEX MATCH "${ARGS_PATTERN_REGEX}" x "${CONTENTS}")
  if(REQUIRED AND NOT x)
    message(FATAL_ERROR "No match to pattern \"${ARGS_PATTERN_REGEX}\" in \"${CONTENTS}\"")
  endif()
  set(${OUTPUT_KEY} "${CMAKE_MATCH_1}")
  string(REPLACE "${ARGS_PATTERN_REPLACE_SEMICOLON}" ";" ${OUTPUT_VAL} "${CMAKE_MATCH_2}")
  set(${OUTPUT_KEY} ${${OUTPUT_KEY}} PARENT_SCOPE)
  set(${OUTPUT_VAL} ${${OUTPUT_VAL}} PARENT_SCOPE)
endfunction()

function(package_key_value OUTPUT_VAR KEY VALUE)
  set(options APPEND)
  set(oneValueArgs APPEND_BEFORE APPEND_AFTER)
  set(multiValueArgs)
  cmake_parse_arguments_key_value_pattern2regex(ARGS ${ARGN})
  if(ARGS_APPEND_BEFORE OR ARGS_APPEND_AFTER)
    set(ARGS_APPEND ON)
  endif()
  set(val "${ARGS_PATTERN}")
  string(REPLACE ";" "${ARGS_PATTERN_REPLACE_SEMICOLON}" value_full "${VALUE}")
  string(REPLACE "<key>" "${KEY}" val "${val}")
  string(REPLACE "<value>" "${value_full}" val "${val}")
  if(ARGS_APPEND)
    if(ARGS_APPEND_BEFORE)
      list(APPEND ${OUTPUT_VAR} "${ARGS_APPEND_BEFORE}")
    endif()
    list(APPEND ${OUTPUT_VAR} ${val})
    if(ARGS_APPEND_AFTER)
      list(APPEND ${OUTPUT_VAR} "${ARGS_APPEND_AFTER}")
    endif()
  else()
    set(${OUTPUT_VAR} ${val})
  endif()
  set(${OUTPUT_VAR} ${${OUTPUT_VAR}} PARENT_SCOPE)
endfunction()

function(package_key_value_list INPUT_VAR)
  set(options APPEND)
  set(oneValueArgs OUTPUT_VAR APPEND_BEFORE APPEND_AFTER)
  set(multiValueArgs)
  cmake_parse_arguments_key_value_pattern2regex(ARGS ${ARGN})
  list(
    APPEND ARGS_PATTERN_CHILD_ARGS_PATTERN APPEND
  )
  if(ARGS_APPEND_BEFORE)
    list(
      APPEND ARGS_PATTERN_CHILD_ARGS_PATTERN
      APPEND_BEFORE "${ARGS_APPEND_BEFORE}"
    )
  endif()
  if(ARGS_APPEND_AFTER)
    list(
      APPEND ARGS_PATTERN_CHILD_ARGS_PATTERN
      APPEND_AFTER "${ARGS_APPEND_AFTER}"
    )
  endif()
  set(INPUT_VAR_CPY ${${INPUT_VAR}})
  if(NOT ARGS_OUTPUT_VAR)
    set(ARGS_OUTPUT_VAR ${INPUT_VAR})
    if(ARGS_APPEND)
      message(FATAL_ERROR "Appending to the input variable may result in strange behavior")
    endif()
  endif()
  set(key)
  set(val)
  if(NOT ARGS_APPEND)
    set(${ARGS_OUTPUT_VAR})
  endif()
  foreach(x IN LISTS INPUT_VAR_CPY)
    extract_key_value(
      ${x} ikey ival
      PATTERN "^${ARGS_PATTERN_REGEX}$" PATTERN_IS_REGEX
      PATTERN_REPLACE_SEMICOLON "${ARGS_PATTERN_REPLACE_SEMICOLON}"
    )
    if(x MATCHES "=" AND NOT ikey)
      message(FATAL_ERROR "Key/value pattern match failed on \"${x}\"")
    endif()
    if(ikey)
      if(key)
        package_key_value(
          ${ARGS_OUTPUT_VAR} ${key} "${val}"
          ${ARGS_PATTERN_CHILD_ARGS_PATTERN}
        )
      endif()
      set(key ${ikey})
      set(val ${ival})
    else()
      list(APPEND val ${x})
    endif()
  endforeach()
  if(key)
    package_key_value(
      ${ARGS_OUTPUT_VAR} ${key} "${val}"
      ${ARGS_PATTERN_CHILD_ARGS_PATTERN}
    )
  endif()
  set(${ARGS_OUTPUT_VAR} ${${ARGS_OUTPUT_VAR}} PARENT_SCOPE)
endfunction()

function(load_cmake_variables CONTENTS)
  cmake_policy(PUSH)
  if(POLICY CMP0057)  # IN_LIST operator
    cmake_policy(SET CMP0057 NEW)
  endif()
  set(options VERBOSE REQUIRED ENV)
  set(oneValueArgs PREFIX SUFFIX LOG_LEVEL)
  set(multiValueArgs VARIABLES)
  cmake_parse_arguments_key_value_pattern2regex(ARGS ${ARGN})
  if(NOT ARGS_LOG_LEVEL)
    if(ARGS_VERBOSE)
      set(ARGS_LOG_LEVEL STATUS)
    else()
      set(ARGS_LOG_LEVEL DEBUG)
    endif()
  endif()
  set(LOADED_VARIABLES)
  foreach(x IN LISTS CONTENTS)
    extract_key_value(
      ${x} key0 val
      ${ARGS_PATTERN_CHILD_ARGS_REGEX}
      REQUIRED
    )
    list(APPEND LOADED_VARIABLES ${key0})
    set(key "${ARGS_PREFIX}${key0}${ARGS_SUFFIX}")
    if(ARGS_VARIABLES AND NOT "${key0}" IN_LIST ARGS_VARIABLES)
      if(ARGS_VERBOSE)
        message(${ARGS_LOG_LEVEL} "SKIPPING LOADED ${key} = ${val}")
      endif()
      continue()
    endif()
    if(ARGS_VERBOSE)
      message(${ARGS_LOG_LEVEL} "LOADED ${key} = ${val}")
    endif()
    if(ARGS_ENV)
      set(ENV{${key}} "${val}")
    else()
      set(${key} ${val} PARENT_SCOPE)
    endif()
  endforeach()
  # string(REPLACE "<key>" "([A-Za-z0-9_]+)" ARGS_PATTERN "${ARGS_PATTERN}")
  # string(REPLACE "<value>" "([^\;]*)" ARGS_PATTERN "${ARGS_PATTERN}")
  # string(REGEX MATCHALL "${ARGS_PATTERN}" matches "${CONTENTS}")
  # foreach(match IN LISTS matches)
  #   string(REGEX MATCH "${ARGS_PATTERN}" x "${match}")
  #   list(APPEND LOADED_VARIABLES ${CMAKE_MATCH_1})
  #   set(key "${ARGS_PREFIX}${CMAKE_MATCH_1}${ARGS_SUFFIX}")
  #   string(REPLACE "-SEMICOLON-" ";" val "${CMAKE_MATCH_2}")
  #   if(ARGS_VARIABLES AND NOT "${CMAKE_MATCH_1}" IN_LIST ARGS_VARIABLES)
  #     if(ARGS_VERBOSE)
  #       message(${ARGS_LOG_LEVEL} "SKIPPING LOADED ${key} = ${val}")
  #     endif()
  #     continue()
  #   endif()
  #   if(ARGS_VERBOSE)
  #     message(${ARGS_LOG_LEVEL} "LOADED ${key} = ${val}")
  #   endif()
  #   if(ARGS_ENV)
  #     set(ENV{${key}} "${val}")
  #   else()
  #     set(${key} ${val} PARENT_SCOPE)
  #   endif()
  # endforeach()
  if(ARGS_VARIABLES AND ARGS_REQUIRED)
    set(MISSING_VARIABLES)
    foreach(var IN LISTS ARGS_VARIABLES)
      if(NOT "${var}" IN_LIST LOADED_VARIABLES)
        list(APPEND MISSING_VARIABLES ${var})
      endif()
    endforeach()
    if(MISSING_VARIABLES)
      message(FATAL_ERROR "Could not locate the following required variables: ${MISSING_VARIABLES}")
    endif()
  endif()
  cmake_policy(POP)
endfunction()

function(dump_cmake_variables)
  set(options VERBOSE INCLUDE_VALUE ENV)
  set(oneValueArgs REGEX PREFIX OUTPUT_VAR LOG_LEVEL
      EXCLUDE_REGEX EXCLUDE_PREFIX)
  set(multiValueArgs VARIABLES)
  set(OUTPUT_PATTERN_ALLOW_EITHER_KEY_OR_VALUE ON)
  cmake_parse_arguments_key_value_pattern2regex_full(ARGS OUTPUT_PATTERN "" ${ARGN})
  if(NOT ARGS_OUTPUT_VAR)
    set(ARGS_VERBOSE ON)
  endif()
  if(NOT ARGS_LOG_LEVEL)
    if(ARGS_VERBOSE)
      set(ARGS_LOG_LEVEL STATUS)
    else()
      set(ARGS_LOG_LEVEL DEBUG)
    endif()
  endif()
  if(ARGS_VARIABLES)
    set(_variableNames ${ARGS_VARIABLES})
  else()
    get_cmake_property(_variableNames VARIABLES)
  endif()
  list (SORT _variableNames)
  if(ARGS_PREFIX)
    if(ARGS_REGEX)
      message(FATAL_ERROR "Both PREFIX and REGEX provided")
    endif()
    set(ARGS_REGEX "^${ARGS_PREFIX}*")
  endif()
  if(ARGS_EXCLUDE_PREFIX)
    if(ARGS_EXCLUDE_REGEX)
      message(FATAL_ERROR "Both EXCLUDE_PREFIX and EXCLUDE_REGEX provided")
    endif()
    set(ARGS_EXCLUDE_REGEX "^${ARGS_EXCLUDE_PREFIX}*")
  endif()
  if(ARGS_OUTPUT_PATTERN AND ARGS_INCLUDE_VALUE)
    message(FATAL_ERROR "Cannot use OUTPUT_PATTERN and INCLUDE_VALUE simultaneously")
  endif()
  if (ARGS_VERBOSE)
    message(${ARGS_LOG_LEVEL} "Variables matching \"${ARGS_REGEX}\" (excluding \"${ARGS_EXCLUDE_REGEX}\"):")
  endif()
  foreach (_variableName ${_variableNames})
    if (ARGS_EXCLUDE_REGEX)
      unset(MATCHED)
      string(REGEX MATCH ${ARGS_EXCLUDE_REGEX} MATCHED ${_variableName})
      if (MATCHED)
        continue()
      endif()
    endif()
    if (ARGS_REGEX)
      unset(MATCHED)
      string(REGEX MATCH ${ARGS_REGEX} MATCHED ${_variableName})
      if (NOT MATCHED)
        continue()
      endif()
    endif()
    if (ARGS_VERBOSE)
      message(${ARGS_LOG_LEVEL} "    ${_variableName}=${${_variableName}}")
    endif()
    if (ARGS_OUTPUT_VAR)
      if(ARGS_OUTPUT_PATTERN)
        package_key_value(
          val ${_variableName} "${${_variableName}}"
          ${ARGS_OUTPUT_PATTERN_CHILD_ARGS_PATTERN}
        )
      elseif(ARGS_INCLUDE_VALUE)
        set(val ${_variableName} ${${_variableName}})
      else()
        set(val ${_variableName})
      endif()
      list(APPEND ${ARGS_OUTPUT_VAR} ${val})
    endif()
  endforeach()
  if (ARGS_OUTPUT_VAR)
    set(${ARGS_OUTPUT_VAR} ${${ARGS_OUTPUT_VAR}} PARENT_SCOPE)
  endif()
endfunction()

macro(propagate_cmake_variables)
  set(_temp_package_vars "${ARGN}")
  foreach (_variableName IN LISTS _temp_package_vars)
    set(${_variableName} ${${_variableName}} PARENT_SCOPE)
  endforeach()
endmacro()

macro(propagate_cmake_variables_regex NAME)
  set(_temp_package_vars "${ARGN}")
  dump_cmake_variables(
    REGEX ${NAME} OUTPUT_VAR _temp_package_vars
  )
  foreach (_variableName IN LISTS _temp_package_vars)
    set(${_variableName} ${${_variableName}} PARENT_SCOPE)
  endforeach()
endmacro()

macro(propagate_cmake_variables_prefix NAME)
  set(_temp_package_vars "${ARGN}")
  dump_cmake_variables(
    REGEX "^${NAME}*" OUTPUT_VAR _temp_package_vars
  )
  foreach (_variableName IN LISTS _temp_package_vars)
    set(${_variableName} ${${_variableName}} PARENT_SCOPE)
  endforeach()
endmacro()

function(copy_cmake_variables src_prefix dst_prefix)
  dump_cmake_variables(PREFIX "${src_prefix}" OUTPUT_VAR SRC_VARS)
  foreach(srcvar IN LISTS SRC_VARS)
    string(REPLACE "${src_prefix}" "${dst_prefix}" dstvar "${srcvar}")
    set(${dstvar} "${${srcvar}}")
  endforeach()
  propagate_cmake_variables_prefix("${dst_prefix}")
endfunction()

function(check_set PREFIX REASON)
  foreach(ivar ${ARGN})
    if(NOT ${PREFIX}_${ivar})
      message(FATAL_ERROR "Argument \"${ivar}\" required${REASON}")
    endif()
  endforeach()
endfunction()

function(check_not_set PREFIX REASON)
  foreach(ivar ${ARGN})
    if(${PREFIX}_${ivar})
      message(FATAL_ERROR "Argument \"${ivar}=${${PREFIX}_${ivar}}\" not allowed${REASON}")
    endif()
  endforeach()
endfunction()

function(check_exclusive_options PREFIX)
  set(options REQUIRED)
  set(oneValueArgs OUTPUT)
  set(multiValueArgs NAMES)
  cmake_parse_arguments(EXCL "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(EXCL_UNPARSED_ARGUMENTS)
    list(APPEND EXCL_NAMES EXCL_UNPARSED_ARGUMENTS)
  endif()
  collect_arguments(
    SET_NAMES "${PREFIX}" "${EXCL_NAMES}"
    ${EXCL_NAMES}
  )
  list(LENGTH SET_NAMES NSET)
  if(NSET EQUAL 0)
    if(EXCL_REQUIRED)
      message(FATAL_ERROR "No option set from ${EXCL_NAMES}")
    endif()
  elseif(NSET EQUAL 1)
    if(EXCL_OUTPUT)
      set(${EXCL_OUTPUT} "${SET_NAMES}" PARENT_SCOPE)
    endif()
  else()
    message(FATAL_ERROR "Conflicting options provided: ${SET_NAMES}")
  endif()
endfunction()

function(set_default var)
  if(NOT ${var})
    set(${var} "${ARGN}" PARENT_SCOPE)
  endif()
endfunction()

function(cmake_parse_arguments_group PREFIX options oneValueArgs multiValueArgs groupArgs)
  cmake_parse_arguments(${PREFIX} "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  foreach(iarg IN LISTS options)
    if(${PREFIX}_${iarg})
      set(${PREFIX}_${iarg} "${iarg}")
    else()
      set(${PREFIX}_${iarg})
    endif()
  endforeach()
  set(${PREFIX}_GROUPED_ARGUMENTS)
  foreach(iarg IN LISTS groupArgs)
    if(${PREFIX}_${iarg})
      list(FIND options "${iarg}" iarg_IDX)
      if(iarg_IDX EQUAL -1)
        list(APPEND ${PREFIX}_GROUPED_ARGUMENTS ${iarg} ${${PREFIX}_${iarg}})
      else()
        list(APPEND ${PREFIX}_GROUPED_ARGUMENTS ${iarg})
      endif()
    endif()
  endforeach()
  propagate_cmake_variables_prefix("${PREFIX}")
endfunction()

function(set_options_to_names PREFIX options)
  foreach(iarg IN LISTS options)
    if(${PREFIX}_${iarg})
      set(${PREFIX}_${iarg} "${iarg}" PARENT_SCOPE)
    else()
      set(${PREFIX}_${iarg} "" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

function(collect_arguments VAR PREFIX options)
  set(out)
  foreach(iarg IN LISTS ARGN)
    if(${PREFIX}_${iarg})
      list(FIND options "${iarg}" iarg_IDX)
      if(iarg_IDX EQUAL -1)
        list(APPEND out ${iarg} ${${PREFIX}_${iarg}})
      else()
        list(APPEND out ${iarg})
      endif()
    endif()
  endforeach()
  set(${VAR} "${out}" PARENT_SCOPE)
endfunction()

function(check_no_unparsed PREFIX)
  if(${PREFIX}_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "Unparsed arguments: ${${PREFIX}_UNPARSED_ARGUMENTS}")
  endif()
endfunction()

function(list_append_with_prefix VAR PREFIX)
  foreach(ivar IN LISTS ARGN)
    list(APPEND ${VAR} ${PREFIX}${ivar})
  endforeach()
  set(${VAR} "${${VAR}}" PARENT_SCOPE)
endfunction()

function(list_intersection VAR)
  list(GET ARGN 0 first)
  list(SUBLIST ARGN 1 -1 OTHER_LISTS)
  set(out)
  foreach(ivar IN LISTS ${first})
    foreach(other IN LISTS OTHER_LISTS)
      list(FIND ${other} ${ivar} other_IDX)
      if(other_IDX EQUAL -1)
        break()
      endif()
    endforeach()
    if(NOT other_IDX EQUAL -1)
      list(APPEND out ${ivar})
    endif()
  endforeach()
  set(${VAR} "${out}" PARENT_SCOPE)
endfunction()

function(test_escape_char_replacement)
  set(TEST_VAR "hello;world")
  foreach(i RANGE 6)
    escape_char_replacement(";" TEST_VAR OUTPUT_VAR RESULT1 LEVEL ${i})
    list(LENGTH RESULT1 RESULT1_LEN)
    message(STATUS "${i}: ${RESULT1} [${RESULT1_LEN}]")
    set(RESULT2 "${RESULT1}")
    list(LENGTH RESULT2 RESULT2_LEN)
    message(STATUS "   ${RESULT2} [${RESULT2_LEN}]")
    foreach(j RANGE ${i})
      set(RESULT2 ${RESULT2})
      list(LENGTH RESULT2 RESULT2_LEN)
      message(STATUS "   ${RESULT2} [${RESULT2_LEN}]")
    endforeach()
  endforeach()
  message(FATAL_ERROR "STOP")
endfunction()

function(escape_char_replacement CHAR VAR)
  set(options)
  set(oneValueArgs LEVEL OUTPUT_VAR)
  set(multiValueArgs)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LEVEL)
    set(ARGS_LEVEL 0)
  endif()
  if(NOT ARGS_OUTPUT_VAR)
    set(ARGS_OUTPUT_VAR ${VAR})
  endif()
  escape_char("${CHAR}" REPLACEMENT LEVEL ${ARGS_LEVEL})
  string(REPLACE "${CHAR}" "${REPLACEMENT}" ${ARGS_OUTPUT_VAR} "${${VAR}}")
  set(${ARGS_OUTPUT_VAR} "${${ARGS_OUTPUT_VAR}}" PARENT_SCOPE)
endfunction()

function(escape_char CHAR OUTPUT_VAR)
  set(options)
  set(oneValueArgs LEVEL)
  set(multiValueArgs)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LEVEL)
    set(ARGS_LEVEL 0)
  endif()
  math(EXPR COUNT "${ARGS_LEVEL}+1")
  string(REPEAT "\\" ${COUNT} ${OUTPUT_VAR})
  set(${OUTPUT_VAR} "${${OUTPUT_VAR}}${CHAR}" PARENT_SCOPE)
endfunction()

function(escape_quotes VAR)
  set(oneValueArgs OUTPUT_VAR)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_OUTPUT_VAR)
    set(ARGS_OUTPUT_VAR ${VAR})
  endif()
  
  set(${ARGS_OUTPUT_VAR} ${${VAR}} PARENT_SCOPE)
endfunction()

function(restore_spaces VAR)
  set(oneValueArgs OUTPUT_VAR)
  cmake_parse_arguments(_ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT _ARGS_OUTPUT_VAR)
    set(_ARGS_OUTPUT_VAR ${VAR})
  endif()
  set(PLACEHOLDER "~SPACE~")
  string(REPLACE "${PLACEHOLDER}" " " out "${${VAR}}")
  set(${_ARGS_OUTPUT_VAR} ${out} PARENT_SCOPE)
endfunction()

function(protect_spaces VAR)
  set(oneValueArgs OUTPUT_VAR)
  cmake_parse_arguments(_ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT _ARGS_OUTPUT_VAR)
    set(_ARGS_OUTPUT_VAR ${VAR})
  endif()
  set(PLACEHOLDER "~SPACE~")
  string(REPLACE " " "${PLACEHOLDER}" out "${${VAR}}")
  set(${_ARGS_OUTPUT_VAR} ${out} PARENT_SCOPE)
endfunction()

function(get_path_sep VAR)
  if(WIN32)
    set(${VAR} "\;" PARENT_SCOPE)
  else()
    set(${VAR} "\:" PARENT_SCOPE)
  endif()
endfunction()

function(extension2language EXT VAR)
  if(EXT STREQUAL ".c")
    set(${VAR} C PARENT_SCOPE)
  elseif(EXT STREQUAL ".cpp")
    set(${VAR} CXX PARENT_SCOPE)
  elseif(EXT STREQUAL ".jl")
    set(${VAR} Julia PARENT_SCOPE)
  elseif(EXT STREQUAL ".py")
    set(${VAR} Python PARENT_SCOPE)
  elseif(EXT STREQUAL ".R")
    set(${VAR} R PARENT_SCOPE)
  elseif(EXT STREQUAL ".m")
    set(${VAR} Matlab PARENT_SCOPE)
  else()
    string(REGEX MATCH "[.][fF]((90)|(95)|(03)|(08)|(18))?$" match ${EXT})
    if(match)
      set(${VAR} Fortran PARENT_SCOPE)
    else()
      message(FATAL_ERROR "Support for extension \"${EXT}\" not implemented")
    endif()
  endif()
endfunction()

function(language2compilerenv language VAR)
  if(language STREQUAL C)
    set(${VAR} "CC" PARENT_SCOPE)
  elseif(language STREQUAL CXX)
    set(${VAR} "CXX" PARENT_SCOPE)
  elseif(language STREQUAL Fortran)
    set(${VAR} "FC" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Support for language \"${language}\" not implemented")
  endif()
endfunction()

function(language2srcext language VAR)
  if(language STREQUAL C)
    set(${VAR} ".c" PARENT_SCOPE)
  elseif(language STREQUAL CXX)
    set(${VAR} ".cpp" PARENT_SCOPE)
  elseif(language STREQUAL Fortran)
    set(${VAR} ".F90" PARENT_SCOPE)
  elseif(language STREQUAL Julia)
    set(${VAR} ".jl" PARENT_SCOPE)
  elseif(language STREQUAL Python)
    set(${VAR} ".py" PARENT_SCOPE)
  elseif(language STREQUAL R)
    set(${VAR} ".R" PARENT_SCOPE)
  elseif(language STREQUAL Matlab)
    set(${VAR} ".m" PARENT_SCOPE)
  else()
    message(ERROR "Support for language \"${language}\" not implemented")
  endif()
endfunction()

function(file2language TARGET VAR)
  cmake_path(GET TARGET EXTENSION TARGET_EXT)
  extension2language(${TARGET_EXT} ${VAR})
  set(${VAR} ${${VAR}} PARENT_SCOPE)
endfunction()

function(get_supported_generators VAR)
  execute_process(
    COMMAND python ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/scripts/check_generators.py
    OUTPUT_VARIABLE RAW_OUTPUT
    COMMAND_ERROR_IS_FATAL ANY
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(output "${CMAKE_GENERATOR}")
  if(WIN32)
    list(APPEND output "MinGW Makefiles")
  endif()
  list(APPEND output ${RAW_OUTPUT})
  # foreach(iout IN LISTS RAW_OUTPUT)
  #   if(NOT iout STREQUAL "${CMAKE_GENERATOR}")
  #     list(APPEND output ${iout})
  #   endif()
  # endforeach()
  list(REMOVE_DUPLICATES output)
  set(${VAR} ${output} PARENT_SCOPE)
endfunction()

function(get_supported_languages VAR)
  set(options COMPILED)
  set(multiValueArgs EXCLUDE)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(ARGS_COMPILED)
    set(out C CXX Fortran)
  else()
    set(out C CXX Fortran Julia Python R Matlab)
  endif()
  if(ARGS_EXCLUDE)
    foreach(ilanguage IN LISTS out)
      list(FIND ARGS_EXCLUDE "${ilanguage}" ilanguage_IDX)
      if(ilanguage_IDX EQUAL -1)
        list(APPEND ${VAR} ${ilanguage})
      endif()
    endforeach()
  else()
    list(APPEND ${VAR} ${out})
  endif()
  set(${VAR} ${${VAR}} PARENT_SCOPE)
endfunction()

function(show_build_info)
  set(oneValueArgs PREFIX LOG_LEVEL)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LOG_LEVEL)
    set(ARGS_LOG_LEVEL DEBUG)
  endif()
  list(APPEND ARGS_UNPARSED_ARGUMENTS LOG_LEVEL ${ARGS_LOG_LEVEL})
  if(ARGS_PREFIX)
    list(APPEND ARGS_UNPARSED_ARGUMENTS PREFIX ${ARGS_PREFIX})
  endif()
  set(
    BASE_ARGUMENTS
    CMAKE_GENERATOR
    CMAKE_VERBOSE_MAKEFILE
    CMAKE_MESSAGE_LOG_LEVEL
    CMAKE_BUILD_PARALLEL_LEVEL
    CMAKE_GNUtoMS
    MSVC_AND_GNU_BUILD
  )
  foreach(iarg IN LISTS BASE_ARGUMENTS)
    message(${ARGS_LOG_LEVEL} "${ARGS_PREFIX}${iarg} = ${${iarg}}")
  endforeach()
  show_compiler_env_vars(${ARGS_UNPARSED_ARGUMENTS})
  show_compilers(${ARGS_UNPARSED_ARGUMENTS})
  show_implicit_libraries(${ARGS_UNPARSED_ARGUMENTS})
endfunction()

function(show_compiler_env_vars)
  set(oneValueArgs PREFIX LOG_LEVEL)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LOG_LEVEL)
    set(ARGS_LOG_LEVEL DEBUG)
  endif()
  get_supported_languages(COMPILED_LANGUAGES COMPILED)
  foreach(ilanguage IN LISTS COMPILED_LANGUAGES)
    language2compilerenv(${ilanguage} ienv)
    message(${ARGS_LOG_LEVEL} "${ARGS_PREFIX}${ienv} = $ENV{${ienv}}")
  endforeach()
endfunction()

function(show_implicit_libraries)
  set(oneValueArgs PREFIX LOG_LEVEL)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LOG_LEVEL)
    set(ARGS_LOG_LEVEL DEBUG)
  endif()
  get_supported_languages(COMPILED_LANGUAGES COMPILED)
  foreach(ilanguage IN LISTS COMPILED_LANGUAGES)
    message(${ARGS_LOG_LEVEL} "${ARGS_PREFIX}CMAKE_${ilanguage}_IMPLICIT_LINK_LIBRARIES = ${CMAKE_${ilanguage}_IMPLICIT_LINK_LIBRARIES}")
  endforeach()
endfunction()

function(show_compilers)
  set(oneValueArgs PREFIX LOG_LEVEL)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_LOG_LEVEL)
    set(ARGS_LOG_LEVEL DEBUG)
  endif()
  get_supported_languages(COMPILED_LANGUAGES COMPILED)
  foreach(ilanguage IN LISTS COMPILED_LANGUAGES)
    message(${ARGS_LOG_LEVEL} "${ARGS_PREFIX}CMAKE_${ilanguage}_COMPILER = ${CMAKE_${ilanguage}_COMPILER}")
  endforeach()
endfunction()

function(sort_files_by_language prefix)
  set(oneValueArgs OUTPUT_LANGUAGES)
  set(multiValueArgs SOURCES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_SOURCES)
    set(ARGS_SOURCES ${ARGS_UNPARSED_ARGUMENTS})
  endif()
  get_supported_languages(LANGUAGES)
  foreach(ilanguage IN LISTS LANGUAGES)
    set(${prefix}_${ilanguage})
  endforeach()
  foreach(ifile IN LISTS ARGS_SOURCES)
    set(ilanguage)
    file2language(${ifile} ilanguage)
    list(APPEND ${prefix}_${ilanguage} ${ifile})
  endforeach()
  set(source_languages)
  foreach(ilanguage IN LISTS LANGUAGES)
    set(${prefix}_${ilanguage} ${${prefix}_${ilanguage}} PARENT_SCOPE)
    if(${prefix}_${ilanguage})
      list(APPEND source_languages ${ilanguage})
    endif()
  endforeach()
  if(ARGS_OUTPUT_LANGUAGES)
    set(${ARGS_OUTPUT_LANGUAGES} ${source_languages} PARENT_SCOPE)
  endif()
endfunction()

function(select_files_by_language language destination)
  get_supported_languages(LANGUAGES)
  set(oneValueArgs OTHER_DESTINATION)
  set(multiValueArgs SOURCES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_SOURCES)
    set(ARGS_SOURCES ${ARGS_UNPARSED_ARGUMENTS})
  endif()
  sort_files_by_language(SRC SOURCES ${ARGS_SOURCES})
  set(sources)
  set(other_sources)
  foreach(ilanguage IN LISTS LANGUAGES)
    if(ilanguage STREQUAL "${language}")
      list(APPEND sources ${SRC_${ilanguage}})
    else()
      list(APPEND other_sources ${SRC_${ilanguage}})
    endif()
  endforeach()
  set(${destination} ${sources} PARENT_SCOPE)
  if(ARGS_OTHER_DESTINATION)
    set(${ARGS_OTHER_DESTINATION} ${other_sources} PARENT_SCOPE)
  endif()
endfunction()

function(inspect_target name)
  set(options)
  set(oneValueArgs LOG_LEVEL PREFIX)
  set(multiValueArgs PROPERTIES)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT TARGET ${name})
    message(FATAL_ERROR "\"${name}\" is not a target")
  endif()
  set_default(ARGS_LOG_LEVEL DEBUG)
  get_property(was_set TARGET ${name} PROPERTY IMPORTED SET)
  if(NOT ARGS_PROPERTIES)
    list(
      APPEND ARGS_PROPERTIES TYPE IMPORTED
      ${CMAKE_PROPERTY_LIST}
    )
    list(REMOVE_DUPLICATES ARGS_PROPERTIES)
  endif()
  message(${ARGS_LOG_LEVEL} "${ARGS_PREFIX}Inspecting target \"${name}\"")
  foreach(property IN LISTS ARGS_PROPERTIES)
    string(REPLACE "<CONFIG>" "${CMAKE_BUILD_TYPE}" property ${property})
    if((NOT IMPORTED) AND (property STREQUAL "LOCATION" OR
                           property MATCHES "^LOCATION_" OR
                           property MATCHES "_LOCATION$"))
      continue()
    endif()
    
    if(property MATCHES "<LANG>")
      continue()
    else()
      get_property(was_set TARGET ${name} PROPERTY ${property} SET)
      if(was_set)
        get_target_property(value ${name} ${property})
        message(${ARGS_LOG_LEVEL} "    ${property} = ${value}")
      endif()
    endif()
  endforeach()
endfunction()

function(set_environment_vars)
  set(oneValueArgs EXISTING KEYPREFIX)
  set(options END_VARS)
  set(multiValueArgs VARS)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if (ARGS_VARS AND NOT ARGS_END_VARS)
    message(FATAL_ERROR "If VARS is provided, END_VARS must be as well.")
  endif()
  if (NOT ARGS_KEYPREFIX)
    set(ARGS_KEYPREFIX ENVKEY_)
  endif()
  string(LENGTH "${ARGS_KEYPREFIX}" KEYPREFIX_LENGTH)
  set(existing)
  foreach(x IN LISTS ARGS_VARS)
    if ("${x}" MATCHES "${ARGS_KEYPREFIX}*")
      if(ikey)
        list(APPEND existing "${ARGS_KEYPREFIX}${ikey}" "$ENV{${ikey}}")
	string(REPLACE ";" " " ival "${ival}")
	set(ENV{${ikey}} "${ival}")
      endif()
      string(SUBSTRING "${x}" ${KEYPREFIX_LENGTH} -1 ikey)
      set(ival)
    else()
      list(APPEND ival ${x})
    endif()
  endforeach()
  if(ikey)
    list(APPEND existing "${ARGS_KEYPREFIX}${ikey}" "$ENV{${ikey}}")
    string(REPLACE ";" " " ival "${ival}")
    set(ENV{${ikey}} "${ival}")
  endif()
  if(ARGS_EXISTING)
    set(${ARGS_EXISTING} ${existing} PARENT_SCOPE)
  endif()
endfunction()

function(add_custom_command_function function)
  set(options PRE_BUILD PRE_LINK POST_BUILD FORCE_OUTPUT
      COMMAND_EXPAND_LISTS USES_TERMINAL VERBATIM)
  set(oneValueArgs MODULE DEST DEST_DIR
      TARGET COMMENT WORKING_DIRECTORY IDSTR)
  set(multiValueArgs FUNCTION_ARGUMENTS GENERATED_FUNCTION_ARGUMENTS
      PRESERVE_VARIABLES COMMAND_ARGUMENTS
      BYPRODUCTS DEPENDS OUTPUT)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  check_exclusive_options(
    ARGS OUTPUT ARGS_EVENT
    NAMES PRE_BUILD PRE_LINK POST_BUILD
  )
  set(ikey)
  set(ival)
  foreach(iarg ${ARGS_GENERATED_FUNCTION_ARGUMENTS})
    if(NOT ikey)
      set(ikey "${iarg}")
    else()
      set(ival "${iarg}")
      list(APPEND ARGS_COMMAND_ARGUMENTS "-DGENERATED_${ikey}=${ival}")
      list(APPEND ARGS_FUNCTION_ARGUMENTS ${ikey} "\$\{GENERATED_${ikey}\}")
      set(ikey)
      set(ival)
    endif()
  endforeach()
  if(NOT ARGS_IDSTR)
    string(RANDOM ARGS_IDSTR)  # Allow user to specify?
    if(ARGS_TARGET)
      set(ARGS_IDSTR "${ARGS_TARGET}_${ARGS_IDSTR}")
    endif()
  endif()
  if(ikey)
    message(FATAL_ERROR "Error processing GENERATED_FUNCTION_ARGUMENTS: ${ARGS_GENERATED_FUNCTION_ARGUMENTS}")
  endif()
  if(ARGS_TARGET)
    get_target_property(TARGET_TYPE ${ARGS_TARGET} TYPE)
    if(TARGET_TYPE STREQUAL "OBJECT_LIBRARY")
      set(ARGS_FORCE_OUTPUT ON)
      if(NOT ARGS_OUTPUT)
        if(NOT ARGS_BYPRODUCTS)
          message(FATAL_ERROR "OUTPUT/BYPRODUCTS required for custom command on OBJECT_LIBRARY target ${ARGS_TARGET}")
        endif()
        set(ARGS_OUTPUT ${ARGS_BYPRODUCTS})
        set(ARGS_BYPRODUCTS)
      endif()
      list(APPEND ARGS_DEPENDS ${ARGS_TARGET} "$<TARGET_OBJECTS:${ARGS_TARGET}>")
      set(ARGS_TARGET)
      set(ARGS_EVENT)
    else()
      if(ARGS_OUTPUT)
        list(APPEND ARGS_BYPRODUCTS ${ARGS_OUTPUT})
        set(ARGS_OUTPUT)
      endif()
    endif()
  endif()
  collect_arguments(
    FUNCTION_ARGS ARGS "${options}"
    MODULE DEST DEST_DIR PRESERVE_VARIABLES IDSTR
    FUNCTION_ARGUMENTS COMMAND_ARGUMENTS
  )
  collect_arguments(
    COMMAND_ARGS ARGS "${options}"
    COMMAND_EXPAND_LISTS USES_TERMINAL VERBATIM
    COMMENT WORKING_DIRECTORY
    BYPRODUCTS DEPENDS
  )
  setup_external_function(
    ${function}
    OUTPUT_COMMAND CUSTOM_COMMAND
    ${FUNCTION_ARGS}
  )
  list(APPEND COMMAND_ARGS COMMAND ${CUSTOM_COMMAND})
  message(DEBUG "CUSTOM_COMMAND = ${CUSTOM_COMMAND}")
  if(ARGS_TARGET)
    if(NOT ARGS_EVENT)
      set(ARGS_EVENT POST_BUILD)
    endif()
    check_not_set(ARGS " when TARGET provided" DEPENDS OUTPUT)
    add_custom_command(
      TARGET ${ARGS_TARGET} ${ARGS_EVENT}
      ${COMMAND_ARGS}
    )
  else()
    check_set(ARGS " when TARGET not provided" OUTPUT)
    check_not_set(
      ARGS " when TARGET not provided" ARGS_EVENT
    )
    add_custom_command(
      OUTPUT ${ARGS_OUTPUT}
      ${COMMAND_ARGS}
    )
    if(ARGS_FORCE_OUTPUT)
      add_custom_target(
        ${ARGS_IDSTR} ALL DEPENDS ${ARGS_OUTPUT}      
      )
    endif()
  endif()
endfunction()

function(setup_external_function function)
  set(options INCLUDE)
  set(oneValueArgs MODULE DEST DEST_DIR OUTPUT_COMMAND IDSTR)
  set(multiValueArgs ARGUMENTS PRESERVE_VARIABLES COMMAND_ARGUMENTS
      FUNCTION_ARGUMENTS)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  list(APPEND ARGS_PRESERVE_VARIABLES
       CMAKE_VERBOSE_MAKEFILE CMAKE_MESSAGE_LOG_LEVEL
       CMAKE_BUILD_PARALLEL_LEVEL)
  if(ARGS_FUNCTION_ARGUMENTS)
    list(APPEND ARGS_ARGUMENTS ${ARGS_FUNCTION_ARGUMENTS})
  endif()
  if(ARGS_UNPARSED_ARGUMENTS)
    list(APPEND ARGS_ARGUMENTS ${ARGS_UNPARSED_ARGUMENTS})
  endif()
  if(NOT ARGS_DEST_DIR)
    set(ARGS_DEST_DIR ${CMAKE_CURRENT_BINARY_DIR})
  endif()
  if(NOT ARGS_DEST)
    if(NOT (ARGS_INCLUDE OR ARGS_OUTPUT_COMMAND))
      message(FATAL_ERROR "Neither DEST, INCLUDE or OUTPUT_COMMAND set")
    endif()
    string(RANDOM DEST_ID)  # Allow user to specify?
    if(ARGS_IDSTR)
      set(DEST_ID "${ARGS_IDSTR}_${DEST_ID}")
    endif()
    cmake_path(
      APPEND ARGS_DEST_DIR "call_${function}_${DEST_ID}.cmake"
      OUTPUT_VARIABLE ARGS_DEST
    )
  endif()
  
  set(ARGS_FUNCTION ${function})
  protect_spaces(ARGS_ARGUMENTS)
  configure_file(
    ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/config/external_function.cmake.in
    ${ARGS_DEST}
    @ONLY
  )
  if(ARGS_INCLUDE)
    include(${ARGS_DEST})
  endif()
  set(OUTPUT_COMMAND ${CMAKE_COMMAND} ${ARGS_COMMAND_ARGUMENTS})
  cmakevars2cmakecliargs(OUTPUT_COMMAND ${ARGS_PRESERVE_VARIABLES})
  list(APPEND OUTPUT_COMMAND -P ${ARGS_DEST})
  if(ARGS_OUTPUT_COMMAND)
    set(${ARGS_OUTPUT_COMMAND} ${OUTPUT_COMMAND} PARENT_SCOPE)
  endif()
endfunction()

function(execute_process_generic)
  set(oneValueArgs TARGET OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  foreach(ivar OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE)
    if(ARGS_${ivar})
      list(APPEND ARGS_UNPARSED_ARGUMENTS ${ivar} ${ARGS_${ivar}})
    endif()
  endforeach()
  if(ARGS_TARGET)
    execute_process_as_target(${ARGS_TARGET} ${ARGS_UNPARSED_ARGUMENTS})
  else()
    execute_process_with_env(${ARGS_UNPARSED_ARGUMENTS})
    foreach(ivar OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE)
      if(ARGS_${ivar})
        set(${ARGS_${ivar}} ${${ARGS_${ivar}}} PARENT_SCOPE)
      endif()
    endforeach()
  endif()
endfunction()

function(execute_process_as_target target)
  set(options ALL VERBATIM USES_TERMINAL COMMAND_EXPAND_LISTS
      # execute_process_with_env arguments
      ENV_VARS_END)
  set(oneValueArgs OUTPUT
      # execute_process_with_env arguments
      ENV_VAR_PREFIX COMMENT
      TIMEOUT WORKING_DIRECTORY
      OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE
      ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE)
  set(multiValueArgs DEPENDS BYPRODUCTS
      # execute_process_with_env arguments
      COMMAND ENV_VARS ENV_VARS_CLEAR CLEAR_COMPILERS
      PREPEND_PATH APPEND_PATH)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  check_no_unparsed()
  foreach(ivar OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE)
    if(ARGS_${ivar})
      message(FATAL_ERROR "\"${var}\" invalid when running process as a custom target (\"${target}\") as the process will not be executed until build time")
      list(APPEND ARGS_UNPARSED_ARGUMENTS ${ivar} ${ARGS_${ivar}})
    endif()
  endforeach()
  if(ARGS_ALL)
    set(ARGS_ALL ALL)
  else()
    set(ARGS_ALL)
  endif()
  collect_arguments(
    PROCESS_ARGS ARGS "${options}"
    COMMENT WORKING_DIRECTORY COMMAND
  )
  collect_arguments(
    EXECUTE_ARGS ARGS "${options}"
    TIMEOUT ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
    ENV_VAR_PREFIX ENV_VARS ENV_VARS_CLEAR CLEAR_COMPILERS
    PREPEND_PATH APPEND_PATH
  )
  collect_arguments(
    COMMAND_ARGS ARGS "${options}"
    VERBATIM USES_TERMINAL COMMAND_EXPAND_LISTS
    DEPENDS BYPRODUCTS
  )
  if(EXECUTE_ARGS)
    setup_external_function(
      "execute_process_with_env" MODULE "GeneralTools"
      DEST ${CMAKE_CURRENT_BINARY_DIR}/execute_${target}.cmake
      OUTPUT_COMMAND TARGET_COMMAND
      ARGUMENTS ${PROCESS_ARGS} ${EXECUTE_ARGS}
    )
    list(APPEND COMMAND_ARGS COMMAND ${TARGET_COMMAND})
  else()
    list(APPEND COMMAND_ARGS ${PROCESS_ARGS})
  endif()
  if(ARGS_OUTPUT)
    add_custom_command(
      OUTPUT ${ARGS_OUTPUT}
      ${COMMAND_ARGS}
    )
    add_custom_target(
      ${target} ${ARGS_ALL}
      DEPENDS ${ARGS_OUTPUT}
    )
  else()
    add_custom_target(
      ${target} ${ARGS_ALL}
      ${COMMAND_ARGS}
    )
  endif()
endfunction()

function(execute_process_with_env)
  set(options ENV_VARS_END)
  set(oneValueArgs ENV_VAR_PREFIX RESULT_VARIABLE COMMENT
      TIMEOUT WORKING_DIRECTORY OUTPUT_VARIABLE ERROR_VARIABLE
      ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE)
  set(multiValueArgs COMMAND ENV_VARS ENV_VARS_CLEAR CLEAR_COMPILERS
      PREPEND_PATH APPEND_PATH)
  cmake_parse_arguments(ARGS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
  if(NOT ARGS_COMMAND)
    message(FATAL_ERROR "COMMAND not provided")
  endif()
  if(NOT ARGS_ENV_VAR_PREFIX)
    if(ARGS_ENV_VARS)
      message(FATAL_ERROR "ENV_VARS provided, but no ENV_VAR_PREFIX")
    else()
      set(ARGS_ENV_VAR_PREFIX "ENVK_")
    endif()
  endif()
  if(ARGS_PREPEND_PATH OR ARGS_APPEND_PATH)
    set(UPDATED_PATH "$ENV{PATH}")
  endif()
  get_path_sep(PATH_SEP)
  if(ARGS_PREPEND_PATH)
    string(REPLACE ";" "${PATH_SEP}" ARGS_PREPEND_PATH "${ARGS_PREPEND_PATH}")
    set(UPDATED_PATH "${ARGS_PREPEND_PATH}${PATH_SEP}${UPDATED_PATH}")
  endif()
  if(ARGS_APPEND_PATH)
    string(REPLACE ";" "${PATH_SEP}" ARGS_APPEND_PATH "${ARGS_APPEND_PATH}")
    set(UPDATED_PATH "${UPDATED_PATH}${PATH_SEP}${APPEND_PATH}")
  endif()
  if(UPDATED_PATH)
    list(APPEND ARGS_ENV_VARS "${ARGS_ENV_VAR_PREFIX}PATH" "${UPDATED_PATH}")
  endif()
  foreach(ilanguage IN LISTS ARGS_CLEAR_COMPILERS)
    language2compilerenv(${ilanguage} ienv)
    list(APPEND ARGS_ENV_VARS_CLEAR ${ienv})
  endforeach()
  foreach(var IN LISTS ARGS_ENV_VARS_CLEAR)
    list(APPEND ARGS_ENV_VARS "${ARGS_ENV_VAR_PREFIX}${var}" "")
  endforeach()
  if(ARGS_ENV_VARS)
    message(DEBUG "ENV_VARS = ${ARGS_ENV_VARS}")
    message(DEBUG "ENV_VAR_PREFIX = ${ARGS_ENV_VAR_PREFIX}")
    set_environment_vars(
      VARS ${ARGS_ENV_VARS} END_VARS
      KEYPREFIX ${ARGS_ENV_VAR_PREFIX}
      EXISTING REPLACED_ENV_VARS
    )
    message(DEBUG "REPLACED_ENV_VARS = ${REPLACED_ENV_VARS}")
  endif()
  if(ARGS_COMMENT)
    message(DEBUG "execute_process_with_env: Running ${ARGS_COMMENT}")
  endif()
  message(STATUS "execute_process_with_env: ARGS_COMMAND = ${ARGS_COMMAND}")
  collect_arguments(
    PROCESS_ARGS ARGS "${options}"
    TIMEOUT WORKING_DIRECTORY
    OUTPUT_VARIABLE ERROR_VARIABLE
    ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
  )
  execute_process(
    COMMAND ${ARGS_COMMAND}
    RESULT_VARIABLE ret
    ${PROCESS_ARGS}
    ${ARGS_UNPARSED_ARGUMENTS}
  )
  if(ARGS_ENV_VARS)
    set_environment_vars(
      VARS ${REPLACED_ENV_VARS} END_VARS
      KEYPREFIX ${ARGS_ENV_VAR_PREFIX}
    )
  endif()
  if(ARGS_RESULT_VARIABLE)
    set(${ARGS_RESULT_VARIABLE} ${ret})
  elseif(NOT ret EQUAL 0)
    message(FATAL_ERROR "Failed to run ${ARGS_COMMAND}")
  endif()
  foreach(ivar OUTPUT_VARIABLE ERROR_VARIABLE RESULT_VARIABLE)
    if(ARGS_${ivar})
      set(${ARGS_${ivar}} ${${ARGS_${ivar}}} PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

