#include "c_wrappers_enums.h"
#include "utils/enums.hpp"

#ifdef __cplusplus /* If this is a C++ compiler, use C linkage */
extern "C" {
#endif


  const int64_t COMM_FLAG_VALID_F = COMM_FLAG_VALID;
  const int64_t COMM_FLAG_GLOBAL_F = COMM_FLAG_GLOBAL;
  const int64_t COMM_FLAG_WORKER_F = COMM_FLAG_WORKER;
  const int64_t COMM_FLAG_DELAYED_OPEN_F = COMM_FLAG_DELAYED_OPEN;
  const int64_t COMM_FLAG_CLIENT_F = COMM_FLAG_CLIENT;
  const int64_t COMM_FLAG_SERVER_F = COMM_FLAG_SERVER;
  const int64_t COMM_FLAG_CLIENT_RESPONSE_F = COMM_FLAG_CLIENT_RESPONSE;
  const int64_t COMM_FLAG_SERVER_RESPONSE_F = COMM_FLAG_SERVER_RESPONSE;
  const int64_t COMM_FLAG_ALWAYS_SEND_HEADER_F = COMM_FLAG_ALWAYS_SEND_HEADER;
  const int64_t COMM_FLAG_ALLOW_MULTIPLE_COMMS_F = COMM_FLAG_ALLOW_MULTIPLE_COMMS;
  const int64_t COMM_FLAG_USED_SENT_F = COMM_FLAG_USED_SENT;
  const int64_t COMM_FLAG_USED_RECV_F = COMM_FLAG_USED_RECV;
  const int64_t COMM_FLAG_EOF_SENT_F = COMM_FLAG_EOF_SENT;
  const int64_t COMM_FLAG_EOF_RECV_F = COMM_FLAG_EOF_RECV;
  const int64_t COMM_FLAG_CLOSE_ON_EOF_RECV_F = COMM_FLAG_CLOSE_ON_EOF_RECV;
  const int64_t COMM_FLAG_CLOSE_ON_EOF_SEND_F = COMM_FLAG_CLOSE_ON_EOF_SEND;
  const int64_t COMM_FLAG_INTERFACE_F = COMM_FLAG_INTERFACE;
  const int64_t COMM_FLAG_DELETE_F = COMM_FLAG_DELETE;
  const int64_t COMM_FLAG_ASYNC_F = COMM_FLAG_ASYNC;
  const int64_t COMM_FLAG_ASYNC_WRAPPED_F = COMM_FLAG_ASYNC_WRAPPED;
  const int64_t COMM_FLAG_SET_OPP_ENV_F = COMM_FLAG_SET_OPP_ENV;
  const int64_t COMM_FLAG_WRAPPER_F = COMM_FLAG_WRAPPER;
  const int64_t COMM_FLAG_FORK_CYCLE_F = COMM_FLAG_FORK_CYCLE;
  const int64_t COMM_FLAG_FORK_BROADCAST_F = COMM_FLAG_FORK_BROADCAST;
  const int64_t COMM_FLAG_FORK_COMPOSITE_F = COMM_FLAG_FORK_COMPOSITE;
  const int64_t COMM_FLAG_FORK_TINE_F = COMM_FLAG_FORK_TINE;
  const int64_t FILE_FLAG_APPEND_F = FILE_FLAG_APPEND;
  const int64_t FILE_FLAG_BINARY_F = FILE_FLAG_BINARY;
  const int64_t FILE_FLAG_READLINE_F = FILE_FLAG_READLINE;
  const int64_t COMM_FLAG_MAX_F = COMM_FLAG_MAX;


#ifdef __cplusplus
}
#endif
