c_stdlib:
  - sysroot                     # [linux]
  - macosx_deployment_target    # [osx]
  - vs                          # [win]
c_stdlib_version:
  - 2.17                        # [linux]
  - 11                          # [osx]
m2w64_c_stdlib:                 # [win]
  - m2w64-sysroot               # [win]
m2w64_c_stdlib_version:         # [win]
  - 12                          # [win]
m2w64_c_compiler:               # [win]
  - gcc                         # [win]
m2w64_c_compiler_version:       # [win]
  - 14                          # [win]
m2w64_cxx_compiler:             # [win]
  - gxx                         # [win]
m2w64_cxx_compiler_version:     # [win]
  - 14                          # [win]
m2w64_fortran_compiler:         # [win]
  - gfortran                    # [win]
m2w64_fortran_compiler_version: # [win]
  - 14                          # [win]