name: Test of conda recipe build
'on':
  push:
    branches-ignore:
     - gh-pages
    tags:
     - '*'
  schedule:
  - cron: 0 10 * * 1
jobs:
  build_conda_recipe:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        # TODO: Revert to windows-latest
        os: [ubuntu-latest, macos-latest, windows-2022]
        python-version: ["3.11"]
        builder: [rattler]  # , rattler-unified]
        include:
          - os: windows-2022
            python-version: "3.11"
            builder: rattler-m2w64
          - os: windows-2022
            python-version: "3.11"
            builder: rattler-m2w64-fortran
          - os: windows-2022
            python-version: "3.11"
            builder: rattler-msvc-gnu
          - os: windows-2022
            python-version: "3.11"
            builder: rattler-flang
          - os: windows-2022
            python-version: "3.11"
            builder: rattler-ifx
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true

      ###################################
      # CONDA SETUP
      ###################################
      - name: Set up MSVC Compiler on windows
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-2022'
      - name: Remove Strawberry Perl from PATH
        if: matrix.os == 'windows-2022'
        shell: pwsh -command ". '{0}'"
        run: |
          $env:PATH = $env:PATH -replace "C:\\Strawberry\\c\\bin;", ""
          "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Get-ChildItem -Path C:\Strawberry -Recurse | Remove-Item -force -recurse
          Remove-Item C:\Strawberry -Force
      - name: Remove Java_Temurin-Hotspot_jdk from PATH
        if: matrix.os == 'windows-2022'
        shell: pwsh -command ". '{0}'"
        run: |
          $env:PATH = $env:PATH -replace "C:\\hostedtoolcache\\windows\\Java_Temurin-Hotspot_jdk\\17.0.19-10\\x64\\bin;", ""
          "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Append
          Get-ChildItem -Path C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk -Recurse | Remove-Item -force -recurse
          Remove-Item C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk -Force
      - name: Set up miniconda test environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: ""
          auto-activate: true
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          miniforge-version: latest
          conda-remove-defaults: true
      - name: Install rattler-build
        run: |
          conda info
          conda list
          conda install rattler-build -y
      - name: Check conda installation
        run: |
          conda info
          conda list
      - name: Build standalone conda recipe (using rattler-build)
        if: matrix.builder == 'rattler'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --no-build-id --no-include-recipe
      # - name: Build unified conda recipe (using rattler-build)
      #   if: matrix.builder == 'rattler-unified'
      #   run: |
      #     rattler-build build --recipe "conda.recipe/recipe-unified.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --no-build-id --no-include-recipe
      # - name: Build unified conda recipe for m2w64 cxx_toolchain_variant (using rattler-build)
      #   if: matrix.builder == 'rattler-m2w64'
      #   run: |
      #     rattler-build build --recipe "conda.recipe/recipe-unified.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant cxx_toolchain_variant=m2w64 --no-build-id --no-include-recipe
      - name: Build conda standalone recipe for m2w64 cxx_toolchain_variant (using rattler-build)
        if: matrix.builder == 'rattler-m2w64'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant cxx_toolchain_variant=m2w64 --variant fortran_toolchain_variant=m2w64 --no-build-id --no-include-recipe
      - name: Build conda standalone recipe for m2w64 fortran_toolchain_variant (using rattler-build)
        if: matrix.builder == 'rattler-m2w64-fortran'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant fortran_toolchain_variant=m2w64 --no-build-id --no-include-recipe
      - name: Build standalone conda recipe with flang fortran compiler (using rattler-build)
        if: matrix.builder == 'rattler-flang'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant fortran_compiler=flang --no-build-id --no-include-recipe
      - name: Build standalone conda recipe with intel ifx fortran compiler (using rattler-build)
        if: matrix.builder == 'rattler-ifx'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant fortran_compiler=ifx --no-build-id --no-include-recipe
      - name: Build standalone conda recipe for MSVC/GNU fortran build (using rattler-build)
        if: matrix.builder == 'rattler-msvc-gnu'
        run: |
          rattler-build build --recipe "conda.recipe/recipe.yaml" --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --variant fortran_toolchain_varient=msvc_gnu --no-build-id --no-include-recipe
      # - name: Build conda recipe (using rattler-build action)
      #   uses: prefix-dev/rattler-build-action@v0.2.34
      #   if: matrix.builder == 'rattler'
      #   with:
      #     upload-artifact: false
      #     build-args: --output-dir $HOME/local_channel/ --variant python=${{ matrix.python-version }} --no-build-id --no-include-recipe


  all_recipes_built:
    runs-on: ubuntu-latest
    name: All recipes were successfully built
    needs: [build_conda_recipe]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
